import type { EmailBlock } from '@citron-systems/citron-ui'

export async function generateBlocksFromPrompt(prompt: string): Promise<EmailBlock[]> {
  await new Promise((r) => setTimeout(r, 1500))

  const id = () => crypto.randomUUID()
  const keyword = prompt.toLowerCase()

  if (keyword.includes('welcome') || keyword.includes('onboarding')) {
    return [
      { id: id(), type: 'heading', content: 'Welcome aboard!' },
      { id: id(), type: 'text', content: 'We are thrilled to have you join us. Here is what you can expect in the next few days.' },
      { id: id(), type: 'button', content: 'Get Started' },
      { id: id(), type: 'divider', content: '' },
      { id: id(), type: 'text', content: 'If you have any questions, reply to this email — a real human will answer.' },
    ]
  }

  return [
    { id: id(), type: 'heading', content: 'Your Email Subject Here' },
    { id: id(), type: 'text', content: `Generated from prompt: "${prompt.slice(0, 80)}"` },
    { id: id(), type: 'image', content: 'https://placehold.co/600x200/1a1a2e/e0e0e0?text=Hero+Image' },
    { id: id(), type: 'text', content: 'Add your main message content here. This was generated by the Marketing AI assistant.' },
    { id: id(), type: 'button', content: 'Call to Action' },
    { id: id(), type: 'divider', content: '' },
    { id: id(), type: 'text', content: 'Thanks for reading — The Marketing Team' },
  ]
}
